import React from 'react';
import {
  Factory,
  ShoppingCart,
  Trash2,
  User,
  LogOut,
  Home,
  LogIn,
  Save,
  Send,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  UserPlus,
  Menu,
  X,
  Mail,
  Phone,
  Package,
  CheckCircle,
  AlertCircle,
  Loader2,
  Loader,
  KeyRound,
  MapPin,
  Clock,
  Users,
  Building2,
  CircleAlert,
  FileText,
  ArrowRight,
  ArrowLeft,
  CircleDashed,
  Info,
  HardHat,
  HelpCircle,
  ShieldCheck,
  RefreshCw,
  PackageCheck,
  ShoppingBag,
  Gauge,
  Zap,
  Star,
  Truck,
  AlertTriangle,
  ArrowUpDown,
  RotateCcw,
  ThumbsUp,
  Circle,
  Disc,
  Minus,
  Wrench,
  Search,
  Link2,
  Layers,
  Settings,
  Shield,
  Warehouse,
  BadgeCheck,
  CalendarDays,
  Calendar,
  ClipboardList,
  CreditCard,
  ExternalLink,
  FileCheck,
  MessageCircleQuestion,
  MessageSquare,
  Newspaper,
  Rss,
  ServerCrash,
  Banknote,
  type LucideProps
} from 'lucide-react';

interface IconProps extends LucideProps {
  name: string;
  fallback?: string;
}

// Карта доступных иконок для оптимизации бандла
const iconMap: Record<string, React.FC<LucideProps>> = {
  Factory,
  ShoppingCart,
  Trash2,
  User,
  LogOut,
  Home,
  LogIn,
  Save,
  Send,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  UserPlus,
  Menu,
  X,
  Mail,
  Phone,
  Package,
  CheckCircle,
  AlertCircle,
  Loader2,
  Loader,
  KeyRound,
  MapPin,
  Clock,
  Users,
  Building2,
  CircleAlert,
  FileText,
  ArrowRight,
  ArrowLeft,
  CircleDashed,
  Info,
  HardHat,
  HelpCircle,
  ShieldCheck,
  RefreshCw,
  PackageCheck,
  ShoppingBag,
  Gauge,
  Zap,
  Star,
  Truck,
  AlertTriangle,
  ArrowUpDown,
  RotateCcw,
  ThumbsUp,
  Circle,
  Disc,
  Minus,
  Wrench,
  Search,
  Link2,
  Layers,
  Settings,
  Shield,
  Warehouse,
  BadgeCheck,
  CalendarDays,
  Calendar,
  ClipboardList,
  CreditCard,
  ExternalLink,
  FileCheck,
  MessageCircleQuestion,
  MessageSquare,
  Newspaper,
  Rss,
  ServerCrash,
  Banknote,
};

const Icon: React.FC<IconProps> = ({ name, fallback = 'CircleAlert', ...props }) => {
  const IconComponent = iconMap[name];

  if (!IconComponent) {
    // Если иконка не найдена, используем fallback иконку
    const FallbackIcon = iconMap[fallback];

    // Если даже fallback не найден, возвращаем пустой span
    if (!FallbackIcon) {
      return <span className="text-xs text-gray-400">[icon]</span>;
    }

    return <FallbackIcon {...props} />;
  }

  return <IconComponent {...props} />;
};

export default Icon;